# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-24 20:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sgf_file', models.TextField()),
                ('player_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_b_requests_created', to=settings.AUTH_USER_MODEL)),
                ('player_w', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_w_requests_created', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
