# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-06 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_logic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='handicap',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='komi',
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AddField(
            model_name='game',
            name='score_b',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='score_w',
            field=models.IntegerField(null=True),
        ),
    ]
